name: GalaxyWars
version: 1.0
main: com.ohmast.galaxy.Plugin
commands:
  createworld:
    description: copys a world
    usage: /<command>
  wtp:
    description: tps to a world
    usage: /<command>